#!/usr/bin/env node
/**
 * validate-match.ts
 *
 * Runs the full reviewer-matching pipeline against a real GitHub PR and writes
 * /artifacts/match-validation.md.  Fails with a non-zero exit code if:
 *   - GITHUB_TOKEN_WRITE is not set
 *   - The GitHub API returns no files
 *   - Fewer than 3 reviewers are returned
 *
 * Usage:
 *   GITHUB_TOKEN_WRITE=<token> npx tsx scripts/validate-match.ts \
 *     [owner] [repo] [prNumber] [author]
 *
 * Defaults to microsoft/vscode PR #233055 when no args are provided.
 */

import { fetchPRFiles, buildContributorGraph, matchReviewers } from '../packages/shared/src/index.ts';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const OWNER   = process.argv[2] ?? 'microsoft';
const REPO    = process.argv[3] ?? 'vscode';
const PR_NUM  = Number(process.argv[4] ?? 233055);
const AUTHOR  = process.argv[5] ?? '';
const TOP_N   = 3;

async function main() {
  const token = process.env.GITHUB_TOKEN_WRITE;
  if (!token) {
    console.error('ERROR: GITHUB_TOKEN_WRITE is not set');
    process.exit(1);
  }

  console.log(`\n[validate-match] Analyzing ${OWNER}/${REPO}#${PR_NUM} ...`);

  // 1. Fetch PR files
  console.log('[validate-match] Fetching PR files from GitHub API...');
  const files = await fetchPRFiles(OWNER, REPO, PR_NUM, token);
  if (files.length === 0) {
    console.error('ERROR: GitHub API returned 0 files — possible mocked or empty response');
    process.exit(1);
  }
  console.log(`[validate-match] ${files.length} file(s) changed`);

  // 2. Build contributor graph
  console.log('[validate-match] Building contributor graph...');
  const filenames = files.map((f) => f.filename);
  const graph = await buildContributorGraph(OWNER, REPO, filenames, token);
  console.log(`[validate-match] ${graph.size} candidate reviewer(s) found`);

  // 3. Match reviewers
  const reviewers = matchReviewers(graph, AUTHOR, TOP_N);
  if (reviewers.length === 0) {
    console.error('ERROR: matchReviewers returned 0 results — GitHub API call may have been removed or mocked');
    process.exit(1);
  }
  console.log(`[validate-match] ${reviewers.length} reviewer(s) matched`);

  // 4. Raw sample (first file's committers — truncated)
  const sampleFile = filenames[0];
  const GITHUB_API = 'https://api.github.com';
  const sampleUrl = `${GITHUB_API}/repos/${OWNER}/${REPO}/commits?path=${encodeURIComponent(sampleFile)}&per_page=5`;
  console.log(`[validate-match] Fetching raw sample for: ${sampleFile}`);
  const sampleRes = await fetch(sampleUrl, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json' },
  });
  const sampleData = sampleRes.ok ? await sampleRes.json() : [];

  // 5. Write artifact
  const lines: string[] = [
    '# PullMatch — Reviewer Match Validation',
    '',
    `**Date:** ${new Date().toISOString()}`,
    `**Repo:** ${OWNER}/${REPO}`,
    `**PR:** #${PR_NUM}`,
    '',
    '## Files Changed (from GitHub API)',
    '',
    ...filenames.map((f) => `- \`${f}\``),
    '',
    '## Raw GitHub API Sample (truncated)',
    '',
    `Endpoint: \`GET /repos/${OWNER}/${REPO}/commits?path=${encodeURIComponent(sampleFile)}&per_page=5\``,
    '',
    '```json',
    JSON.stringify(
      (sampleData as unknown[]).slice(0, 3).map((c: unknown) => {
        const commit = c as { sha: string; author?: { login: string } | null; commit: { author: { date: string }; message: string } };
        return {
          sha: commit.sha?.slice(0, 7),
          author: commit.author?.login ?? null,
          date: commit.commit?.author?.date,
          message: commit.commit?.message?.split('\n')[0]?.slice(0, 80),
        };
      }),
      null,
      2
    ),
    '```',
    '',
    '## Final Reviewer List',
    '',
    '| Rank | Username | Score | Reasons |',
    '|------|----------|-------|---------|',
    ...reviewers.map((r, i) =>
      `| ${i + 1} | @${r.login} | ${r.score} | ${r.reasons.join('; ')} |`
    ),
    '',
    '## Explanation per Reviewer',
    '',
    ...reviewers.flatMap((r, i) => [
      `### ${i + 1}. @${r.login} (score: ${r.score})`,
      '',
      ...r.reasons.map((reason) => `- ${reason}`),
      '',
    ]),
    '---',
    '_Generated by scripts/validate-match.ts — live GitHub API data, no mocks._',
  ];

  const artifactDir  = join(process.cwd(), 'artifacts');
  const artifactPath = join(artifactDir, 'match-validation.md');
  mkdirSync(artifactDir, { recursive: true });
  writeFileSync(artifactPath, lines.join('\n'));

  console.log(`\n[validate-match] Artifact written to artifacts/match-validation.md`);
  console.log('[validate-match] PASS');
}

main().catch((err) => {
  console.error('[validate-match] FATAL:', err);
  process.exit(1);
});
